data:
  channels: 12
  color_jitter: 0.0
  cont_local: 3
  data_root: ./datasets/ADNI
  dataset: ANDI
  gaussian_dequantization: false
  image_size: 128
  logit_transform: false
  num_frames: 1
  num_frames_cond: 1
  num_frames_future: 1
  num_workers: 16
  prob_mask_cond: 0.0
  prob_mask_future: 0.0
  prob_mask_sync: false
  random_flip: false
  rescaled: true
  test_list_path: ./datasets/andi/test-list.txt
  train_list_path: ./datasets/andi/train-list.txt
  uniform_dequantization: false
  val_list_path: ./datasets/andi/val-list.txt
model:
  arch: unetmore
  attn_resolutions:
  - 8
  - 16
  - 32
  ch_mult:
  - 1
  - 1
  - 2
  - 3
  - 4
  cond_emb: false
  conditional: true
  depth: deeper
  dropout: 0.1
  ema: true
  ema_rate: 0.999
  gamma: false
  n_head_channels: 64
  ngf: 256
  noise_in_cond: false
  nonlinearity: swish
  normalization: InstanceNorm++
  num_classes: 1000
  num_res_blocks: 3
  output_all_frames: false
  sigma_begin: 0.02
  sigma_dist: linear
  sigma_end: 0.0001
  spade: false
  spade_dim: 128
  spec_norm: false
  time_conditional: true
  type: v1
  version: DDPM
optim:
  amsgrad: false
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.0001
  optimizer: Adam
  warmup: 5000
  weight_decay: 0.0
sampling:
  batch_size: 100
  ckpt_id: 0
  clip_before: true
  consistent: true
  data_init: false
  denoise: true
  fid: false
  final_only: true
  fvd: true
  init_prev_t: -1.0
  inpainting: false
  interpolation: false
  max_data_iter: 100000
  n_interpolations: 15
  n_steps_each: 0
  num_frames_pred: 28
  num_samples4fid: 10000
  num_samples4fvd: 10000
  one_frame_at_a_time: false
  preds_per_test: 1
  ssim: true
  step_lr: 0.0
  subsample: 100
  train: false
test:
  batch_size: 100
  begin_ckpt: 5000
  end_ckpt: 300000
training:
  L1: true
  batch_size: 12
  log_all_sigmas: false
  log_freq: 100
  n_epochs: 1000000
  n_iters: 10000001
  sample_freq: 1000
  sampling_batch_size: 2
  snapshot_freq: 50000
  snapshot_sampling: true
  val_freq: 50000
